# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Profile Update
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 0/6 * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ✨ General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "[Actions] chore: update ${filename}"

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: glsl
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      - name: ✨ Addon
        uses: lowlighter/metrics@latest
        with:
          filename: addon.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "[Actions] chore: update ${filename}"

          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}

          template: classic
          base: ""
          config_timezone: Asia/Shanghai

          plugin_fortune: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: history
          plugin_steam: yes
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_achievements_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: "76561199048891793"
          plugin_music: yes
          plugin_music_playlist: >-
            https://music.youtube.com/playlist?list=PLL_8Z7sl-sjx_yhMeKREbHbnqZQ-a1XCW

      - name: ✨ Setup repo
        uses: actions/checkout@v4
      - name: ✨ Reorganize resources
        run: |
          git pull --no-edit && mv -fv *.svg ./res/svg/

      - name: ✨ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Actions] chore: reorganize assets"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          file_pattern: "*.svg"
